/**
 * import-export.js — two-step product import.
 *   1. Upload file  → POST /api/import/products  (parse only, returns rows)
 *   2. Review modal → POST /api/import/products/commit (creates products,
 *      auto-generating SKUs and seeding stock)
 *
 * The template only carries the columns a user can reasonably fill in
 * offline; SKUs are generated by the server and category / supplier /
 * location are picked in the review modal.
 */
(function () {
  'use strict';

  const TEMPLATE_FIELDS = [
    'name',
    'initial_quantity',
    'unit_of_measure',
    'reorder_level',
    'unit_price',
    'expiry_date',
  ];

  const token = sessionStorage.getItem('token');
  const headers = { 'Authorization': `Bearer ${token}` };

  // ── Upload UI refs ──
  const dropZone     = document.getElementById('drop-zone');
  const fileInput    = document.getElementById('file-input');
  const browseBtn    = document.getElementById('browse-btn');
  const filePreview  = document.getElementById('file-preview');
  const fileName     = document.getElementById('file-name');
  const clearFileBtn = document.getElementById('clear-file-btn');
  const uploadBtn    = document.getElementById('upload-btn');
  const importResult = document.getElementById('import-result');

  // ── Modal refs ──
  const modal = document.getElementById('import-review-modal');
  const tbody = document.getElementById('review-tbody');
  const bulkLoc = document.getElementById('bulk-location');
  const bulkCat = document.getElementById('bulk-category');
  const bulkSup = document.getElementById('bulk-supplier');
  const bulkApplyBtn  = document.getElementById('bulk-apply-btn');
  const reviewCancel  = document.getElementById('review-cancel-btn');
  const reviewConfirm = document.getElementById('review-confirm-btn');

  let selectedFile = null;
  let reviewRows = []; // working copy of parsed rows + per-row picks
  let locations = [], categories = [], suppliers = [];

  // ── Helpers ──
  function escapeHtml(s) {
    return String(s ?? '')
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#039;');
  }

  function showImportError(message, errors) {
    importResult.style.display = 'block';
    let html = `<div class="import-errors"><h4>Import failed</h4>` +
      `<p style="color:var(--fg-2);font-size:12px;margin-bottom:8px">${escapeHtml(message || '')}</p>`;
    if (Array.isArray(errors) && errors.length) {
      html += '<ul>';
      errors.forEach((e) => {
        html += `<li>Row ${e.row}: ${escapeHtml((e.errors || []).join(', '))}</li>`;
      });
      html += '</ul>';
    }
    html += '</div>';
    importResult.innerHTML = html;
  }

  function clearImportResult() {
    importResult.style.display = 'none';
    importResult.innerHTML = '';
  }

  // ── File selection ──
  browseBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    fileInput.click();
  });
  dropZone.addEventListener('click', () => fileInput.click());
  fileInput.addEventListener('change', () => {
    if (fileInput.files.length > 0) selectFile(fileInput.files[0]);
  });
  ['dragenter', 'dragover'].forEach((evt) => {
    dropZone.addEventListener(evt, (e) => {
      e.preventDefault();
      dropZone.classList.add('dragover');
    });
  });
  dropZone.addEventListener('dragleave', () => dropZone.classList.remove('dragover'));
  dropZone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropZone.classList.remove('dragover');
    if (e.dataTransfer.files.length > 0) selectFile(e.dataTransfer.files[0]);
  });

  function selectFile(file) {
    const ext = file.name.split('.').pop().toLowerCase();
    if (!['csv', 'xlsx'].includes(ext)) {
      alert('Only .csv and .xlsx files are accepted.');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      alert('File exceeds 5MB limit.');
      return;
    }
    selectedFile = file;
    fileName.textContent = file.name;
    filePreview.style.display = 'flex';
    uploadBtn.style.display = 'inline-flex';
    uploadBtn.disabled = false;
    clearImportResult();
  }

  clearFileBtn.addEventListener('click', () => {
    selectedFile = null;
    fileInput.value = '';
    filePreview.style.display = 'none';
    uploadBtn.style.display = 'none';
    uploadBtn.disabled = true;
    clearImportResult();
  });

  // ── Upload (parse step) ──
  uploadBtn.addEventListener('click', async () => {
    if (!selectedFile) return;

    // Guard: only admins can import. Staff hit the popup instead of a 403.
    const currentUser = (() => { try { return JSON.parse(sessionStorage.getItem('user') || '{}'); } catch { return {}; } })();
    if (currentUser.role !== 'admin' && window.Invex && window.Invex.denyAccess) {
      window.Invex.denyAccess({
        title: 'Admins only',
        message: 'Importing products is restricted to administrators. You can still export from this page.',
      });
      return;
    }

    uploadBtn.disabled = true;
    uploadBtn.textContent = 'Parsing…';

    const formData = new FormData();
    formData.append('file', selectedFile);

    try {
      const res = await fetch('/api/import/products', {
        method: 'POST',
        headers,
        body: formData,
      });
      const data = await res.json();
      if (!data.success) {
        showImportError(data.message, data.errors);
        return;
      }
      // Pre-load the option lists, then open the review modal.
      await loadReferenceData();
      openReviewModal(data.data || []);
    } catch (err) {
      showImportError('Network error — could not connect.');
    } finally {
      uploadBtn.disabled = false;
      uploadBtn.textContent = 'Upload & import';
    }
  });

  // ── Review modal ──
  async function loadReferenceData() {
    const [locRes, catRes, supRes] = await Promise.all([
      fetch('/api/locations', { headers }),
      fetch('/api/categories', { headers }),
      fetch('/api/suppliers', { headers }),
    ]);
    const [locJson, catJson, supJson] = await Promise.all([
      locRes.json(), catRes.json(), supRes.json(),
    ]);
    locations  = (locJson.success ? locJson.data : []) || [];
    categories = (catJson.success ? catJson.data : []) || [];
    suppliers  = (supJson.success ? supJson.data : []) || [];

    fillBulkSelect(bulkLoc, 'Location…',          locations);
    fillBulkSelect(bulkCat, 'Category…',          categories);
    fillBulkSelect(bulkSup, 'Supplier (optional)…', suppliers);
  }

  function fillBulkSelect(sel, placeholder, items) {
    sel.innerHTML = `<option value="">${placeholder}</option>` +
      items.map((i) => `<option value="${i.id}">${escapeHtml(i.name)}</option>`).join('');
  }

  function rowOptions(items, selected, includeNone) {
    let html = `<option value="">—</option>`;
    if (includeNone) html = `<option value="">—</option>`;
    return html + items.map((i) =>
      `<option value="${i.id}" ${String(i.id) === String(selected) ? 'selected' : ''}>${escapeHtml(i.name)}</option>`
    ).join('');
  }

  function renderReviewTable() {
    tbody.innerHTML = reviewRows.map((r, i) => `
      <tr data-idx="${i}" class="${r._error ? 'row-error' : ''}">
        <td class="name-cell">
          <input type="text" class="form-control" data-field="name" value="${escapeHtml(r.name)}" />
          ${r._error ? `<div class="row-error-msg">${escapeHtml(r._error)}</div>` : ''}
        </td>
        <td class="num num-cell">
          <input type="number" min="0" class="form-control" data-field="initial_quantity" value="${escapeHtml(r.initial_quantity ?? 0)}" />
        </td>
        <td class="uom-cell">
          <input type="text" class="form-control" data-field="unit_of_measure" value="${escapeHtml(r.unit_of_measure || 'pcs')}" />
        </td>
        <td class="num num-cell">
          <input type="number" min="0" class="form-control" data-field="reorder_level" value="${escapeHtml(r.reorder_level ?? 0)}" />
        </td>
        <td class="num num-cell">
          <input type="number" min="0" step="0.01" class="form-control" data-field="unit_price" value="${escapeHtml(r.unit_price ?? 0)}" />
        </td>
        <td class="date-cell">
          <input type="date" class="form-control" data-field="expiry_date" value="${escapeHtml(r.expiry_date || '')}" />
        </td>
        <td class="pick-cell">
          <select class="form-control" data-field="location_id">${rowOptions(locations, r.location_id)}</select>
        </td>
        <td class="pick-cell">
          <select class="form-control" data-field="category_id">${rowOptions(categories, r.category_id)}</select>
        </td>
        <td class="pick-cell">
          <select class="form-control" data-field="supplier_id">${rowOptions(suppliers, r.supplier_id, true)}</select>
        </td>
      </tr>
    `).join('');
  }

  // Capture per-cell edits back into reviewRows
  tbody.addEventListener('change', (e) => {
    const tr = e.target.closest('tr');
    if (!tr) return;
    const idx = parseInt(tr.dataset.idx, 10);
    const field = e.target.dataset.field;
    if (!field || Number.isNaN(idx)) return;
    let value = e.target.value;
    if (['initial_quantity', 'reorder_level'].includes(field)) value = value === '' ? 0 : parseInt(value, 10);
    if (field === 'unit_price') value = value === '' ? 0 : parseFloat(value);
    if (['location_id', 'category_id', 'supplier_id'].includes(field)) {
      value = value === '' ? null : parseInt(value, 10);
    }
    reviewRows[idx][field] = value;
    if (reviewRows[idx]._error) {
      delete reviewRows[idx]._error;
      tr.classList.remove('row-error');
      const msg = tr.querySelector('.row-error-msg');
      if (msg) msg.remove();
    }
  });

  bulkApplyBtn.addEventListener('click', () => {
    const loc = bulkLoc.value ? parseInt(bulkLoc.value, 10) : null;
    const cat = bulkCat.value ? parseInt(bulkCat.value, 10) : null;
    const sup = bulkSup.value ? parseInt(bulkSup.value, 10) : null;
    reviewRows.forEach((r) => {
      if (loc !== null) r.location_id = loc;
      if (cat !== null) r.category_id = cat;
      if (sup !== null) r.supplier_id = sup;
    });
    renderReviewTable();
  });

  function openReviewModal(rows) {
    reviewRows = rows.map((r) => ({
      ...r,
      location_id: null,
      category_id: null,
      supplier_id: null,
    }));
    renderReviewTable();
    modal.style.display = 'flex';
  }

  function closeReviewModal() {
    modal.style.display = 'none';
    reviewRows = [];
    tbody.innerHTML = '';
    bulkLoc.value = '';
    bulkCat.value = '';
    bulkSup.value = '';
  }

  reviewCancel.addEventListener('click', closeReviewModal);
  modal.addEventListener('click', (e) => { if (e.target === modal) closeReviewModal(); });

  reviewConfirm.addEventListener('click', async () => {
    // Client-side check before round-trip
    const missing = reviewRows
      .map((r, i) => ({ i, missing: !r.location_id || !r.category_id }))
      .filter((x) => x.missing);
    if (missing.length) {
      missing.forEach(({ i }) => {
        reviewRows[i]._error = 'Location and category are required';
      });
      renderReviewTable();
      return;
    }

    reviewConfirm.disabled = true;
    reviewConfirm.textContent = 'Importing…';
    try {
      const res = await fetch('/api/import/products/commit', {
        method: 'POST',
        headers: { ...headers, 'Content-Type': 'application/json' },
        body: JSON.stringify({ rows: reviewRows }),
      });
      const data = await res.json();
      if (data.success) {
        closeReviewModal();
        // Reset upload card
        selectedFile = null;
        fileInput.value = '';
        filePreview.style.display = 'none';
        uploadBtn.style.display = 'none';
        importResult.style.display = 'block';
        importResult.innerHTML = `<div class="import-success">✓ ${escapeHtml(data.message)}</div>`;
      } else {
        // Mark error rows in the table and re-render
        if (Array.isArray(data.errors)) {
          data.errors.forEach((e) => {
            const idx = (e.row | 0) - 1;
            if (reviewRows[idx]) reviewRows[idx]._error = (e.errors || []).join(', ');
          });
        }
        renderReviewTable();
        alert(data.message || 'Some rows are missing required fields.');
      }
    } catch (err) {
      alert('Network error — please try again.');
    } finally {
      reviewConfirm.disabled = false;
      reviewConfirm.textContent = 'Import';
    }
  });

  // ── Template download (new schema) ──
  const downloadTemplateBtn = document.getElementById('download-template-btn');
  if (downloadTemplateBtn) {
    downloadTemplateBtn.addEventListener('click', (e) => {
      e.preventDefault();
      const rows = [
        ['Sample Product',      '50', 'pcs', '10', '25.50',  ''],
        ['Expiry Tracked Item', '20', 'box', '5',  '150.00', '2026-12-31'],
      ];
      const csv = [TEMPLATE_FIELDS, ...rows].map((r) => r.join(',')).join('\n');
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'invex_product_template.csv';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    });
  }

  // ── Export download (unchanged) ──
  function downloadExport(type, format) {
    const url = `/api/export/${type}?format=${format}`;
    fetch(url, { headers })
      .then((res) => {
        if (!res.ok) throw new Error('Export failed');
        return res.blob();
      })
      .then((blob) => {
        const objUrl = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = objUrl;
        a.download = `${type}.${format}`;
        document.body.appendChild(a);
        a.click();
        URL.revokeObjectURL(objUrl);
        a.remove();
      })
      .catch(() => alert('Export failed. Please try again.'));
  }

  document.querySelectorAll('.ie-export-item').forEach((item) => {
    item.addEventListener('click', () => {
      const type   = item.dataset.type;
      const format = item.dataset.format || 'csv';
      downloadExport(type, format);
    });
  });

  window.downloadExport = downloadExport;
})();
